services:
  db:
    container_name: postgres_db
    restart: unless-stopped
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app_taskmanager
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    env_file:
      - ./app/.env
    restart: unless-stopped
    depends_on:
      - redis
      - db

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_app.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

  migrate:
    container_name: migrate
    build: .
    depends_on:
      - db
      - app
    command: alembic upgrade head

volumes:
  db_data:
