version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    restart: always
    depends_on:
      - redis
      - db

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_app.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

  migrate:
    container_name: migrate
    build: .
    depends_on:
      - db
      - app
    command: alembic upgrade head

volumes:
  db_data:
