"""create categories table

Revision ID: 7525eff33a07
Revises: b5ffec98ea4f
Create Date: 2024-10-16 16:51:19.394719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7525eff33a07"
down_revision: Union[str, None] = "b5ffec98ea4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_categories_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_name"), "categories", ["name"], unique=True
    )
    op.add_column(
        "tasks", sa.Column("category_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_tasks_category_id_categories"),
        "tasks",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_category_id_categories"), "tasks", type_="foreignkey"
    )
    op.drop_column("tasks", "category_id")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
